on:
  push:
    branches:
      - 'main'
  pull_request:
  
name: Test FFI

jobs:
    build:
      name: Build
      runs-on: macos-latest
      steps:
        - name: install elan
          run: |
            set -o pipefail
            curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
            ./elan-init -y --default-toolchain none
            echo "$HOME/.elan/bin" >> $GITHUB_PATH

        - uses: actions/checkout@v4

        - name: run Lean tests
          run: lake exe test

  