on:
  push:
    branches:
      - 'main'
  pull_request:
  
name: Test FFI

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: leanprover/lean-action@v1
          with:
            test: false
            use-mathlib-cache: true
            use-github-cache: false
            build-args: "-R -Kwerror"
        - name: run Lean tests
          run: lake exe test

  